version: 2
updates:
  - package-ecosystem: "npm"
    allow:
      - dependency-type: "production"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ "dependencies" ]
    target-branch: "master"
    reviewers:
      - "johannestegner"

  - package-ecosystem: "npm"
    allow:
      - dependency-type: "development"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "dev-dependencies" ]
    target-branch: "master"
    reviewers:
      - "johannestegner"
