template: |
  ## Changes

  $CHANGES

  ---
  Thanks to the contributors:

  $CONTRIBUTORS

tag-template: "$NEXT_PATCH_VERSION"

categories:
  - title: 'Features:'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes:'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Security:'
    labels:
      - security
      - sec
      - vulnerability
      - vuln

exclude-labels:
  - 'dependencies'
