on:
  pull_request:
    branches:
      - dependency-updates

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 12.x, 11.x 10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Test on node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-versionn }}
      - name: Install & test.
        run: |
          npm ci
          npm test
        env:
          CI: true
          NODE_ENV: development
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Comment to auto-merge
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets. BotToken }}
        with:
          actor: "accounts+github@jitesoft.com"
          args: comment "@dependabot merge"

